# Generated by Django 6.0 on 2026-01-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
