# Generated by Django 6.0 on 2026-01-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_order_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
