# Generated by Django 6.0 on 2026-01-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cover',
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
